Initial frontend commit using yarn, and inclusion of testing-library module
ubclaunchpad/foodies pull request #9
Opened 2020-10-21 05:48 UTC by richardyjtian

Resolves #2

2020-10-24 22:13 UTC, engineereng approved these changes

2020-10-25 03:53 UTC, andrewzulaybar requested changes
This looks like a good start! Do you think you'd be able to add support for TypeScript? I think that's the only thing left that we'd need :)

2020-10-26 06:08 UTC, andrewzulaybar approved these changes
Looks good to me! Feel free to merge it in :)

2020-10-27 03:40 UTC, ericrkuo approved these changes

2020-10-27 17:00 UTC, merged